apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-gateway-32
  description: Plataforma de pagamentos digitais
  annotations:
    github.com/project-slug: bonett-labs/payment-gateway-32
spec:
  type: website
  lifecycle: experimental
  owner: group:default/fintech-squad
  system: system:default/payments-platform
