apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-f
  description: teste f
  annotations:
    github.com/project-slug: bonett-labs/teste-f
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/bonett-labs/teste-f
  links:
    - url: https://github.com/bonett-labs/teste-f
      title: GitHub Repository
      icon: github
  tags:
    - react
    - typescript
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: group:default/tribe-devtools
  system: system:default/dtp-devtools-platform
