apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: game-arena-7
  description: Ecossistema de jogos online
  annotations:
    github.com/project-slug: bonett-labs/game-arena-7
spec:
  type: website
  lifecycle: experimental
  owner: group:default/game-studio
  system: system:default/gaming-platform
