apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stream-central-33
  description: Experiencias de streaming e conteudo
  annotations:
    github.com/project-slug: bonett-labs/stream-central-33
spec:
  type: website
  lifecycle: experimental
  owner: group:default/media-engineering
  system: system:default/media-streaming-platform
