apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: logistics-hub-1
  description: Operacoes e logistica integrada
  annotations:
    github.com/project-slug: bonett-labs/logistics-hub-1
spec:
  type: website
  lifecycle: experimental
  owner: group:default/supply-chain-tech
  system: system:default/logistics-platform
