apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iot-pulse-9
  description: Gestao de dispositivos conectados
  annotations:
    github.com/project-slug: bonett-labs/iot-pulse-9
spec:
  type: website
  lifecycle: experimental
  owner: group:default/device-ops
  system: system:default/iot-platform
