apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "dtp-devtools-platform-test-s3-b-dev"
  annotations:
    backstage.io/source-location: url:https://github.com/bonett-labs/dtp-s3/tree/develop
    zentry.io/resource-type: s3
    zentry.io/resource-name: "dtp-test-s3-b"
    zentry.io/resource-file: "dtp-test-s3-b.tf"
    zentry.io/environment: "dev"
spec:
  type: infrastructure
  lifecycle: "dev"
  owner: group:default/tribe-devtools
  system: "system:default/dtp-devtools-platform"
