apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dtp-teste-a
  description: teste a
  annotations:
    github.com/project-slug: bonett-labs/
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/bonett-labs/
  links:
    - url: https://github.com/bonett-labs/
      title: GitHub Repository
      icon: github
  tags:
    - react
    - typescript
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: group:default/alliance-product-engineering
  system: system:default/dtp-devtools-platform
