apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-y
  description: test y
  annotations:
    github.com/project-slug: bonett-labs/teste-y
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/bonett-labs/teste-y
  links:
    - url: https://github.com/bonett-labs/teste-y
      title: GitHub Repository
      icon: github
  tags:
    - react
    - typescript
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: group:default/alliance-platform-infrastructure
  system: system:default/dtp-devtools-platform
